version: "3.8"

services:
  backend:
    build: ./backend
    container_name: micro-win-backend
    ports:
      - "8080:80"

  frontend:
    build: ./frontend
    container_name: micro-win-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
